# Generated by Django 4.2.13 on 2024-05-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_livres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='id_livre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
